# Generated by Django 5.0.6 on 2024-06-02 12:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mistnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno místnosti musí být vyplněno'}, max_length=50, verbose_name='Název místnosti')),
                ('kapacita', models.IntegerField(default=0, help_text='Kapacita musí být vyplněna', verbose_name='Kapacita')),
            ],
            options={
                'verbose_name': 'Místnost',
                'verbose_name_plural': 'Místnosti',
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('zakaznik', 'Zákazník'), ('zamestnanec', 'Zaměstnanec'), ('brigadnik', 'Brigádník'), ('cvicitel', 'Cvičitel')], default='zakaznik', max_length=15, verbose_name='Typ účtu')),
                ('predplatne', models.CharField(choices=[('ucet', 'Účet'), ('permanentka', 'Permanentka'), ('clen', 'Člen')], default='ucet', max_length=15, verbose_name='Typ předplatného')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('prijmeni', models.CharField(help_text='Zadejte přijmení uživatele', max_length=100, verbose_name='Přijmení')),
                ('telefon', models.CharField(help_text='Zadejte telefon v podobě: +420 777 777 777', max_length=16, validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$', 'Nesprávně zadané telefonní číslo')], verbose_name='Telefon')),
                ('email', models.EmailField(error_messages={'blank': 'Pole nesmí být prázdné', 'invalid': 'Neplatná e-mailová adresa', 'unique': 'E-mailová adresa musí být jedinečná'}, max_length=254, unique=True, verbose_name='Email')),
                ('adresa', models.CharField(blank=True, max_length=100, verbose_name='Adresa')),
                ('psc', models.PositiveIntegerField(help_text='Zadejte poštovní směrovací číslo (bez mezery)', validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Nesprávně zadané poštovní směrovací číslo')], verbose_name='PSČ')),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoba',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Lekce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název lekce', max_length=100, verbose_name='Název lekce')),
                ('start', models.DateTimeField()),
                ('konec', models.DateTimeField()),
                ('mistnost', models.ForeignKey(error_messages={'blank': 'Místnost musí být zvolena'}, on_delete=django.db.models.deletion.CASCADE, to='HealthSync.mistnost', verbose_name='Místnosti')),
                ('cvicitel', models.ForeignKey(error_messages={'blank': 'Cvičitel musí být zvolen'}, on_delete=django.db.models.deletion.CASCADE, to='HealthSync.osoba', verbose_name='Cvičitel')),
            ],
            options={
                'verbose_name': 'Lekce',
                'verbose_name_plural': 'Lekce',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField(default=django.utils.timezone.now)),
                ('lekce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthSync.lekce', verbose_name='Název lekce')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthSync.osoba', verbose_name='Jméno zákazníka')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
                'ordering': ['zakaznik'],
            },
        ),
    ]
