# Generated by Django 5.0.6 on 2024-06-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthSync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervace',
            name='cas',
        ),
    ]
