# Generated by Django 5.0.6 on 2024-06-04 06:19

import HealthSync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthSync', '0002_remove_rezervace_cas'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='fotka',
            field=models.ImageField(blank=True, upload_to=HealthSync.models.get_image_path, verbose_name='Fotografie'),
        ),
    ]
